# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.supportedFilesystems = [ "ntfs" "nfs"];
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/64456cb5-b9e8-4883-a2c8-0e4bb4fd3070";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6ED4-3934";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/run/media/pandy/BigSSD" =
    { device = "/dev/disk/by-uuid/4AD08239D0822AF1";
      fsType = "ntfs";
      options = [ "rw" "uid=1000"];
    };

  # optional, but ensures rpc-statsd is running for on demand mounting
#  fileSystems."/run/media/pandy/SlowSmallSSD" =
#    { device = "/dev/disk/by-uuid/8C9055BB9055AC88";
#      fsType = "ntfs-3g";
#      options = [ "rw" "uid=1000"];
#    };
#fileSystems."/home/pandy/mnt" = {
#  device = "pandy@192.168.1.96:/";
#  fsType = "sshfs";
#  options = [
#    "nodev"
#    "noatime"
#    "allow_other"
#    "IdentityFile=/home/pandy/.ssh/id_ed25519"
#  ];
#};
  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.bluetooth.enable = true; # enables support for Bluetooth
  hardware.bluetooth.powerOnBoot = true; # powers up the default Bluetooth controller on boot
}
